// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evuqxlfdvsdcfvphqifh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2dXF4bGZkdnNkY2Z2cGhxaWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODkyNjcsImV4cCI6MjA2NTU2NTI2N30.ioYzxsykyb-mVquJTJJzFVbNcEJKEN5lfMPau6cnyw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});